name: deploy

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            # - name: Install Pagefind v${{ env.PAGEFIND_VERSION }}
            #   uses: supplypike/setup-bin@v3
            #   with:
            #       uri: "https://github.com/CloudCannon/pagefind/releases/download/v${{ env.PAGEFIND_VERSION }}/pagefind_extended-v${{ env.PAGEFIND_VERSION }}-x86_64-unknown-linux-musl.tar.gz"
            #       name: "pagefind_extended"
            #       version: ${{env.PAGEFIND_VERSION}}

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "latest"
                  extended: true

            - name: Build Web
              run: hugo --minify

            - name: Install nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - run: npx -y pagefind --source public

            - name: Deploy Web
              uses: peaceiris/actions-gh-pages@v3
              with:
                  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
                  EXTERNAL_REPOSITORY: Huang-Zifeng/Huang-Zifeng.github.io
                  PUBLISH_DIR: ./public
                  KEEP_FILES: false
                  PUBLISH_BRANCH: cf-pages
                  commit_message: ${{ github.event.head_commit.message }}